spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/geo_postgis
    username: postgres
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
          open-in-view: false
          database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect

